React Carousel Component
neldaza/c1021-code-solutions pull request #131
Opened 2022-02-11 01:14 UTC by neldaza

https://user-images.githubusercontent.com/88061673/153523234-19132a6a-5848-466c-b146-53baf4b79f79.mov

2022-02-11 01:17 UTC, thebearingedge requested changes
Please do this without a library. Just raw React.

2022-02-11 22:34 UTC, neldaza commented
Raw React Version 
https://user-images.githubusercontent.com/88061673/153679832-ff06415c-a101-4702-bf3b-bcc9f18354e4.mov

2022-02-11 22:35 UTC, neldaza commented
Raw React Recording



https://user-images.githubusercontent.com/88061673/153679976-60d5ceee-92fc-439f-87be-3667238d203c.mov

2022-02-13 22:39 UTC, thebearingedge requested changes
Ok, pretty good, just a few refinements.

2022-02-13 22:39 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +      ],
The images should be passed to the carousel as a prop.

2022-02-13 22:39 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +      if (this.state.currentPhoto === 4) {
Instead of hard-coding a number here, try basing your logic off of the length of the array.

2022-02-13 22:39 UTC, thebearingedge commented on react-carousel-component/src/carousel.jsx
> +    if (event.target.className === 'arrow left relative-fifty previous-arrow' && this.state.currentPhoto === 0) {
We don't modify elements like this in React, instead pass props to elements in `render()` to change them.

2022-02-16 01:21 UTC, thebearingedge requested changes
woah this is getting a little out of control. please fix your code to just have `carousel.jsx` and `index.jsx` you shouldn't need an app component at all

2022-02-16 16:13 UTC, thebearingedge requested changes

2022-02-16 20:00 UTC, thebearingedge approved these changes

2022-02-16 20:01 UTC, merged