Javascript Carousel First Draft
neldaza/c1021-code-solutions pull request #58
Opened 2021-11-03 23:37 UTC by neldaza

https://user-images.githubusercontent.com/88061673/140233352-753c1fa3-7737-4125-b468-8a5f45286258.mov

2021-11-03 23:40 UTC, codingcodymiller requested changes
Nice work so far! One note to get you started:

2021-11-03 23:40 UTC, codingcodymiller commented on javascript-carousel/main.js
> +}
This is all very manual. If you want to add additional images, you need to make a new function every time. Instead, I recommend you make an array of all the possible `src` values for the image in the carousel, and then make a variable to keep track of the index for the current image. You should also make use of a loop over the dots to show the one for the current image as solid, and the rest as hollow. I suggest putting a `data-` attribute on each dot icon, maybe something like `data-image-index`

2022-02-09 21:04 UTC, thebearingedge requested changes

2022-02-09 21:04 UTC, thebearingedge commented on javascript-carousel/main.js
> +}
This is pretty much the same code twice. If you update the current image and just roll with it, you don't need all of this code.

2022-02-09 21:04 UTC, thebearingedge commented on javascript-carousel/main.js
> +  }
This is pretty much the same code twice. If you update the current image and just roll with it, you don't need all of this code.

2022-02-09 21:24 UTC, thebearingedge approved these changes

2022-02-09 21:28 UTC, merged