Array Filter First Draft
neldaza/c1021-code-solutions pull request #95
Opened 2021-12-07 23:23 UTC by neldaza

2021-12-07 23:23 UTC, neldaza commented
![Screen Shot 2021-12-07 at 3 23 46 PM](https://user-images.githubusercontent.com/88061673/145121349-198f5c22-938a-453b-a05f-cfb8afb0c436.png)

2021-12-08 00:30 UTC, thebearingedge requested changes

2021-12-08 00:30 UTC, thebearingedge commented on array-filter/main.js
> +  }
You should be able to complete these without writing any loops.

2021-12-08 00:46 UTC, thebearingedge approved these changes

2021-12-08 00:47 UTC, merged